workflows:
  flutter-android-debug:
    name: Flutter Android Debug
    environment:
      flutter: stable
      android: true
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK in debug mode
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
