name: groq_chat_flutter
description: A Groq Chat application using Flutter

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.19.0
  path_provider: ^2.1.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Added flutter_lints

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
